#!/usr/bin/env python3
"""Generates the Android launcher icon from one definition.

The mark is a padlock in the app's theme seed colour: a shackle, a rounded
body, and a keyhole knocked out of it.

Every size is drawn at 4x and downsampled rather than being scaled from a
single master, so edges stay clean at 48px where most icons turn to mush.

    python tools/make-icons.py

Writes both the legacy square icon and the Android 8+ adaptive pair. Adaptive
icons are the reason the mark is drawn twice at different scales: launchers
mask the foreground to whatever shape the device uses and may animate it, so
the art has to sit inside a safe zone covering the middle 72 of 108 units.
Artwork sized for the legacy icon gets its edges clipped off.

Requires Pillow.
"""

from __future__ import annotations

import pathlib
import sys

try:
    from PIL import Image, ImageDraw
except ImportError:
    sys.exit("Pillow is required:  python -m pip install pillow")

REPO = pathlib.Path(__file__).resolve().parent.parent
RES = REPO / "android" / "app" / "src" / "main" / "res"

SS = 4  # supersample factor

# Matches AppTheme.seed in lib/theme.dart. The gradient runs to a darker shade
# of the same hue so the icon reads as one colour rather than two.
SEED = (0x5A, 0x4F, 0xCF)
DEEP = (0x2A, 0x24, 0x6B)
MARK = (0xFF, 0xFF, 0xFF)

# Launcher icon sizes. Adaptive foreground and background are 108/48 larger
# than the legacy icon at the same density.
LEGACY = {
    "mipmap-mdpi": 48,
    "mipmap-hdpi": 72,
    "mipmap-xhdpi": 96,
    "mipmap-xxhdpi": 144,
    "mipmap-xxxhdpi": 192,
}
ADAPTIVE = {name: round(px * 108 / 48) for name, px in LEGACY.items()}


def _gradient(n: int) -> Image.Image:
    img = Image.new("RGB", (n, n), SEED)
    d = ImageDraw.Draw(img)
    for y in range(n):
        t = y / max(n - 1, 1)
        d.line(
            [(0, y), (n, y)],
            fill=tuple(int(a + (b - a) * t) for a, b in zip(SEED, DEEP)),
        )
    return img


def _padlock(d: ImageDraw.ImageDraw, n: int, scale: float, hole) -> None:
    """Draws the padlock centred in an n-px canvas, `scale` of the canvas."""
    # Work in a 100-unit space, then map through `scale` about the centre.
    def u(v: float) -> float:
        return (50 + (v - 50) * scale) * n / 100.0

    width = max(int(7 * scale * n / 100.0), 1)
    # Shackle first, so the body overlaps where its feet meet the case.
    d.arc([u(30), u(22), u(70), u(62)], start=180, end=360, fill=MARK, width=width)
    d.rounded_rectangle(
        [u(26), u(46), u(74), u(80)],
        radius=int(8 * scale * n / 100.0),
        fill=MARK,
    )
    d.ellipse([u(45), u(56), u(55), u(66)], fill=hole)
    d.polygon(
        [(u(47.5), u(63)), (u(52.5), u(63)), (u(54), u(73)), (u(46), u(73))],
        fill=hole,
    )


def legacy(size: int) -> Image.Image:
    n = size * SS
    img = _gradient(n)
    _padlock(ImageDraw.Draw(img), n, 1.0, DEEP)
    return img.resize((size, size), Image.LANCZOS)


def foreground(size: int) -> Image.Image:
    """Transparent, with the mark inside the adaptive safe zone."""
    n = size * SS
    img = Image.new("RGBA", (n, n), (0, 0, 0, 0))
    # 72/108 is the guaranteed-visible circle; a little under it leaves room
    # for the parallax launchers apply when the icon is dragged.
    _padlock(ImageDraw.Draw(img), n, 0.60, (0, 0, 0, 0))
    return img.resize((size, size), Image.LANCZOS)


def background(size: int) -> Image.Image:
    n = size * SS
    return _gradient(n).resize((size, size), Image.LANCZOS)


ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/make-icons.py -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
"""


def main() -> None:
    if not RES.is_dir():
        sys.exit(f"No Android res directory at {RES}")

    written = 0
    for folder, px in LEGACY.items():
        out = RES / folder
        out.mkdir(parents=True, exist_ok=True)
        legacy(px).save(out / "ic_launcher.png")
        written += 1

    for folder, px in ADAPTIVE.items():
        out = RES / folder
        foreground(px).save(out / "ic_launcher_foreground.png")
        background(px).save(out / "ic_launcher_background.png")
        written += 2

    # Only ic_launcher. No ic_launcher_round: android:roundIcon would have to
    # resolve on API 24-25 too, where anydpi-v26 does not apply and no round
    # PNG exists. Adaptive icons already let the launcher mask to whatever
    # shape it wants from API 26, which covers every device this would matter
    # on.
    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(ADAPTIVE_XML, encoding="utf-8")
    written += 1

    print(f"wrote {written} files under {RES}")


if __name__ == "__main__":
    main()
